id: P99D69916
initial_creation_type: ocr
source_metadata:
  volumes:
    93b0009680f942e0b12b2f5fd9c590bf:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: རྣལ་འབྱོར་གྱི་རྒྱུད་དཔལ་གདན་བཞི་པའི་སྒྲུབ་ཐབས།
      total_pages: 2043
      volume_number: 13
